[west]
account = "account"
api_key = "apikey"

[telegram]
chat_id = 12345678
token = "token:token"

[slack]
channel_id = "CHANNEL"
token = "token"

[line]
access_token = "Channel Access Token"
id = ""
secret = "Channel Secret"
