[cert]
C = "TW"
CN = "test.com"
L = "Taipei"
O = "ops-cli"
OU = "IT"
ST = ""
dnsNames = ["*.test.com"]
emailAddresses = []
ipAddresses = []
uris = []
year = 1

# https://discord.com/
[discord]
channel_id = "channelID"
token = "token"

[encrypt]
key = ""

# https://www.west.cn/
[icp]
account = "account"
api_key = "apikey"

# https://developers.line.biz/
[line]
access_token = "Channel Access Token"
id = ""
secret = "Channel Secret"

[redis]
auth = "007008009"
db = 0
host = "127.0.0.1"
port = "6379"
user = "redis"

# https://slack.com
[slack]
channel_id = "CHANNEL"
token = "token"

# https://telegram.org/
[telegram]
chat_id = "12345678"
token = "token:token"
