# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    # You may remove this if you don't use go modules.
    - ./scripts/generate.bash
    # you may remove this if you don't need go generate
    # - go generate ./...

builds:
  - flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ldflags:
      - -s -w -X github.com/linzeyan/ops-cli/cmd.appVersion={{ .Tag }} -X github.com/linzeyan/ops-cli/cmd.appBuildTime={{ .Date }} -X github.com/linzeyan/ops-cli/cmd.appCommit={{ .Commit }}

snapshot:
  name_template: "{{ .Tag }}_{{ .ShortCommit }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

archives:
  - name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true

    replacements:
      # darwin: Darwin
      # linux: Linux
      # windows: Windows
      386: i386
      # amd64: x86_64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: packages
    file_name_template: "{{ .ConventionalFileName }}"
    maintainer: ZeYanLin <zeyanlin@outlook.com>
    license: Apache-2.0
    homepage: https://github.com/linzeyan/ops-cli
    bindir: /usr/bin
    contents:
      - src: ./completion/ops-cli.bash
        dst: /usr/share/bash-completion/completions/ops-cli
        file_info:
          mode: 0644
      - src: ./completion/ops-cli.fish
        dst: /usr/share/fish/completions/ops-cli.fish
        file_info:
          mode: 0644
      - src: ./completion/ops-cli.zsh
        dst: /usr/share/zsh/vendor-completions/_ops-cli
        file_info:
          mode: 0644
      - src: ./doc/*
        dst: /usr/share/man/man3/
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/ops-cli/copyright
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
    # dependencies:
    #   - git
    # recommends:
    #   - golang
    version_metadata: git

brews:
  - name: "{{ .ProjectName }}"
    homepage: https://github.com/linzeyan/homebrew-tools
    tap:
      owner: linzeyan
      name: homebrew-tools
