---
default: true
MD013:
  line_length: 100
  heading_line_length: 80
  code_blocks: false
  tables: true
  headings: true
  headers: true
  strict: false
  stern: false
MD051: false # link-fragments Link fragments should be valid
