name: release

on:
  push:
    tags:
      - "*"

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check config
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: check

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.OPSCLI_TOKEN }}

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: docker login -u zeyanlin -p ${{ secrets.DOCKERHUB }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: scripts/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          build-args: |
            Tag=${GITHUB_REF#refs/tags/}
            Commit=${GITHUB_SHA}
            Date=$(date '+%Y-%m-%dT%H:%M:%SZ')
          tags: |
            zeyanlin/ops-cli:latest
            zeyanlin/ops-cli:${GITHUB_REF#refs/tags/}
