name: release

on:
  push:
    tags:
      - "*"

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Check config
        uses: goreleaser/goreleaser-action@v6
        with:
          version: v2.8.2
          # version: latest
          args: check

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: v2.8.2
          # version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.OPSCLI_TOKEN }}

      - name: Delete older releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 1
        env:
          GITHUB_TOKEN: ${{ secrets.OPSCLI_TOKEN }}

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Login to Docker Hub
        run: docker login -u zeyanlin -p ${{ secrets.DOCKERHUB }}

      - name: Set output
        id: vars
        run: |
          echo "tag=${GITHUB_REF#refs/*/}">>$GITHUB_ENV
          echo "commit=${GITHUB_SHA}">>$GITHUB_ENV
          echo "date=$(date '+%Y-%m-%dT%H:%M:%SZ')">>$GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          file: scripts/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          build-args: |
            Tag=${{ env.tag }}
            Commit=${{ env.commit }}
            Date=${{ env.date }}
          tags: |
            zeyanlin/ops-cli:latest
            zeyanlin/ops-cli:${{ env.tag }}
