name: test

on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - "cmd/**"
      - "test/**"
      - "main.go"
    # paths-ignore:
    #   - ".github/**"
    #   - "scripts/**"
    #   - "vendor/**"
    #   - "LICENSE"
    #   - "README.md"
    #   - ".config**"
    #   - ".gitignore"
    #   - ".go**"
    #   - ".pre-commit-config.yaml"

permissions:
  contents: read

env:
  CGO_ENABLED: 0

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        goVersion:
          - 18
        os:
          - macos
          - ubuntu
          - windows
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: read # for golangci/golangci-lint-action to fetch pull requests
    name: "lint ${{ matrix.os }} | 1.${{ matrix.goVersion }}.x"
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: "Install go1.${{ matrix.goVersion }}.x"
        uses: actions/setup-go@v3
        with:
          go-version: 1.${{ matrix.goVersion }}.x

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2
        with:
          args: --timeout=5m
          version: v1.48.0

  go-test:
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        goVersion:
          - 18
        os:
          - macos
          - ubuntu
          - windows

    name: "go-test ${{ matrix.os }} | 1.${{ matrix.goVersion }}.x"
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: "Install go1.${{ matrix.goVersion }}.x"
        uses: actions/setup-go@v3
        with:
          go-version: 1.${{ matrix.goVersion }}.x

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ matrix.goVersion }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Run go test
        run: go test ./test/.
