name: test

on: [push]

permissions:
  contents: read

jobs:
  golangci-lint:
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: read # for golangci/golangci-lint-action to fetch pull requests
    name: "lint"
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # v3
        with:
          go-version: ~1.19

      - name: Checkout
        uses: actions/checkout@b0e28b5ac45a892f91e7d036f8200cf5ed489415 # v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc # v3
        with:
          args: --timeout=5m

  test-go:
    name: "test-go"
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run go test
        run: go test test/*.go

  test-unix:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu
          - macOS
        go:
          - 17
          - 18
    name: "${{ matrix.platform }} | 1.${{ matrix.go }}.x"
    runs-on: ${{ matrix.platform }}-latest
    steps:
      - name: "Install go1.${{ matrix.go }}.x"
        uses: actions/setup-go@v2
        with:
          go-version: 1.${{ matrix.go }}.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run test script
        run: ./scripts/test.bash all

  test-win:
    name: MINGW64
    defaults:
      run:
        shell: msys2 {0}
    runs-on: windows-latest
    steps:
      - name: Set line break types
        shell: bash
        run: git config --global core.autocrlf input

      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            git
            mingw-w64-x86_64-go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run test script
        run: ./scripts/test.bash all
