name: test

on: [push]

permissions:
  contents: read

env:
  CGO_ENABLED: 0

jobs:
  golangci-lint:
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: read # for golangci/golangci-lint-action to fetch pull requests
    name: "lint"
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # v3
        with:
          go-version: ~1.19

      - name: Checkout
        uses: actions/checkout@b0e28b5ac45a892f91e7d036f8200cf5ed489415 # v3
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc # v3
        with:
          args: --timeout=5m

  test:
    strategy:
      fail-fast: false
      matrix:
        goVersion:
          - 17
          - 18
          - 19
        os:
          - macos
          - ubuntu
          - windows

    name: "${{ matrix.os }} | 1.${{ matrix.goVersion }}.x"
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: "Install go1.${{ matrix.goVersion }}.x"
        uses: actions/setup-go@v3
        with:
          go-version: 1.${{ matrix.goVersion }}.x

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ matrix.goVersion }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Run go test
        run: go test test/*.go
